apiVersion: kubeonkube.clay.io/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: cluster
    app.kubernetes.io/instance: cluster-sample
    app.kubernetes.io/part-of: kube-on-kube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-on-kube
  name: cluster-sample
spec:
  # TODO(user): Add fields here
