//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024 Clay.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"kube-on-kube/api"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cluster) DeepCopyInto(out *Cluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cluster.
func (in *Cluster) DeepCopy() *Cluster {
	if in == nil {
		return nil
	}
	out := new(Cluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCondition) DeepCopyInto(out *ClusterCondition) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCondition.
func (in *ClusterCondition) DeepCopy() *ClusterCondition {
	if in == nil {
		return nil
	}
	out := new(ClusterCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterList) DeepCopyInto(out *ClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterList.
func (in *ClusterList) DeepCopy() *ClusterList {
	if in == nil {
		return nil
	}
	out := new(ClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperation) DeepCopyInto(out *ClusterOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperation.
func (in *ClusterOperation) DeepCopy() *ClusterOperation {
	if in == nil {
		return nil
	}
	out := new(ClusterOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperationList) DeepCopyInto(out *ClusterOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperationList.
func (in *ClusterOperationList) DeepCopy() *ClusterOperationList {
	if in == nil {
		return nil
	}
	out := new(ClusterOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperationSpec) DeepCopyInto(out *ClusterOperationSpec) {
	*out = *in
	if in.HostsConfRef != nil {
		in, out := &in.HostsConfRef, &out.HostsConfRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.VarsConfRef != nil {
		in, out := &in.VarsConfRef, &out.VarsConfRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.SSHAuthRef != nil {
		in, out := &in.SSHAuthRef, &out.SSHAuthRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.EntrypointSHRef != nil {
		in, out := &in.EntrypointSHRef, &out.EntrypointSHRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.ActionSource != nil {
		in, out := &in.ActionSource, &out.ActionSource
		*out = new(ActionSource)
		**out = **in
	}
	if in.ActionSourceRef != nil {
		in, out := &in.ActionSourceRef, &out.ActionSourceRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.PreHook != nil {
		in, out := &in.PreHook, &out.PreHook
		*out = make([]HookAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PostHook != nil {
		in, out := &in.PostHook, &out.PostHook
		*out = make([]HookAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperationSpec.
func (in *ClusterOperationSpec) DeepCopy() *ClusterOperationSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterOperationStatus) DeepCopyInto(out *ClusterOperationStatus) {
	*out = *in
	if in.JobRef != nil {
		in, out := &in.JobRef, &out.JobRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterOperationStatus.
func (in *ClusterOperationStatus) DeepCopy() *ClusterOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.HostsConfRef != nil {
		in, out := &in.HostsConfRef, &out.HostsConfRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.VarsConfRef != nil {
		in, out := &in.VarsConfRef, &out.VarsConfRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.KubeConfRef != nil {
		in, out := &in.KubeConfRef, &out.KubeConfRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.SSHAuthRef != nil {
		in, out := &in.SSHAuthRef, &out.SSHAuthRef
		*out = new(api.DataRef)
		**out = **in
	}
	if in.PreCheckRef != nil {
		in, out := &in.PreCheckRef, &out.PreCheckRef
		*out = new(api.DataRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterStatus) DeepCopyInto(out *ClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ClusterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterStatus.
func (in *ClusterStatus) DeepCopy() *ClusterStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HookAction) DeepCopyInto(out *HookAction) {
	*out = *in
	if in.ActionSource != nil {
		in, out := &in.ActionSource, &out.ActionSource
		*out = new(ActionSource)
		**out = **in
	}
	if in.ActionSourceRef != nil {
		in, out := &in.ActionSourceRef, &out.ActionSourceRef
		*out = new(api.DataRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HookAction.
func (in *HookAction) DeepCopy() *HookAction {
	if in == nil {
		return nil
	}
	out := new(HookAction)
	in.DeepCopyInto(out)
	return out
}
